### ISSUE TITLE
Best way to get base URI or baseUrl of executing script?

### ISSUE THREAD

**Issue by binki** [fbbdev/node-fastcgi#11]
I have done some fiddling around and searching through the codebase and I came up with this as a way to discover the URI of the script being executed:

    let unqualifiedBaseUri = request.cgiParams.SCRIPT_NAME;

What I am really wondering is: is this a supported way to do this sort of thing? Will `cgiParams` always be around? I found `// NOTE: Backward compatibility` next to it in the code. If its deprecated, what is the future API to use for this?

The issue with standardization is that this is not really a scenario supported by node’s `http` module. All it does is provide the [raw URI sent by the client](https://nodejs.org/api/http.html#http_message_url). I would like to be able to place my script anywhere and automatically handle its URIs which would match `PATH_INFO` but be capable of generating URIs which relative to the URI that would cause `PATH_INFO` to be `/` or empty. E.g., if my script handles `/asdf` and `/dah` and I access it at `http://example.org/blah/script.cgi/asdf` I want to be able to generate the correct URI for `/dah` which would be `http://example.org/blah/script.cgi/dah`.

In ExpressJS, its augmented request object has a [`baseUrl`](https://expressjs.com/en/4x/api.html#req.baseUrl) property. This property is equivalent to `request.cgiParams.SCRIPT_NAME` in node-fastcgi AFAICT. If node-fastcgi extended the request object this same way, you could get something like the following should hopefully be enough to automount an ExpressJS app with zero configuration (this glue could be put in its own npm module…):

```
var express = require('express');

// Set up any express app like normal.
var app = express();
app.get('/hi', function (request, response) {
  response.send(`hello. Visit bye at: http://${request.hostname}${request.baseUrl}/bye`);
});
app.get('/bye', function (request, response) {
  response.send('bye?');
});

var rootApp = express();
var automount = {};
require('node-fastcgi').createServer(function (request) {
  // Compatibility shim
  request.baseUrl = request.baseUrl || request.cgiParams.SCRIPT_NAME;
  if (!automount[request.baseUrl]) {
    rootApp.use(request.baseUrl, app);
    automount[request.baseUrl] = true;
  }
  // ExpressJS gets confused if we set baseUrl because
  // each mount uses its parent’s baseUrl plus its submountpoint
  // as its baseUrl.
  request.baseUrl = undefined;
  return rootApp.apply(this, arguments);
}).listen();
```

I’d like to get this closer to being just `.createServer(app).listen()` if possible.

Thoughts?

**Comment by fbbdev** [comment]
Older versions of this module used a custom request object to emulate the one from the `http` module. This resulted in conflicts with the express framework, so I changed to a real request object with a fake socket. With this change CGI-related APIs have moved to the socket object and I kept those on the request object only for compatibility. The current API to access CGI params is `request.socket.params`, as explained [here](https://github.com/fbbdev/node-fastcgi#the-socket-object).

As regards the base url problem, you would equally get into it if you were using the plain `http` module or any other transport, and likewise you'd need a wrapper to configure the application. I can't add an express-specific API to my module; also, adding a `baseUrl` property would hurt other applications not expecting it. However, you could use a middleware to avoid all that cruft in your example:

```js
const express = require("express");

var app = express();

// Middleware
app.use((req, res, next) => {
  req.baseUrl = req.socket.params.SCRIPT_NAME;
  req.url = req.url.slice(req.baseUrl.length);
  next();
});

// Routes
app.get('/hi', (req, res) => {
  res.send(`hello. Visit bye at: http://${req.hostname}${req.baseUrl}/bye`);
});

app.get('/bye', (req, res) {
  res.send('bye?');
});

require('node-fastcgi').createServer(app).listen();
```

If you can't add a middleware in the app, you can create a wrapper like you did in your example:

```js
const express = require('express');

var app = express();

// Routes
app.get('/hi', (req, res) => {
  res.send(`hello. Visit bye at: http://${req.hostname}${req.baseUrl}/bye`);
});

app.get('/bye', (req, res) {
  res.send('bye?');
});

// Wrapper and middleware
var wrapper = express();

wrapper.use((req, res, next) => {
  req.baseUrl = req.socket.params.SCRIPT_NAME;
  req.url = req.url.slice(req.baseUrl.length);
  next();
}, app);

require('node-fastcgi').createServer(wrapper).listen();
```

I have not tested this one but I think it should work.

**Comment by binki** [comment]
OK, the embodiment of my “way” of solving this for now is https://github.com/binki/http-autodetect if you want to criticize it ;-). Basically my module claims to support a couple different deployment scenarios and provides a `getBaseUrl(req)` function which should support all of those scenarios. And that now probes correctly for `request.socket.params.SCRIPT_NAME` to support `node-fastcgi`.

For Express support, I haven’t yet figured out how to get the middleware approach you suggested to work, but I have spent most of my time trying to just figure out how to organize things and haven’t had a chance to investigate that properly. So I’m still using the method of creating a container app and automounting things for now: https://github.com/binki/express-http-autodetect .

I do see now when you point it out clearly how the `request.socket.params` API is explained and now I know where to find that. I think I would miss it if I were newly reading the README, though. Might I suggest you add a reference to `socket.params` to https://github.com/fbbdev/node-fastcgi#request-url-components (as that’s where I kept ending up when trying to figure out how to read `SCRIPT_NAME` for myself ;-))?

Thanks for the help!

**Comment by fbbdev** [comment]
I hope I did not sound dismissive or pedantic in my previous message, I didn't mean to, but I have a knack for this :grin:

I really like your http-autodetect, nice idea! :+1: I look forward to using it myself. I'll open some issues there to suggest improvements.

I'm also definitely going to improve the README according to your suggestions.

Getting back to express integration: the more I think about it, the more I believe the middleware solution is the right way to go. Your package express-http-autodetect could provide both a middleware function for custom app configurations and the wrapper function - based on the middleware - for quick setup.

**Comment by binki** [comment]
> I hope I did not sound dismissive or pedantic in my previous message

Not at all! I assume you’re replying to my use of the word “criticism” which normally has a bad connotation, didn’t mean that ;-).
