### ISSUE TITLE
CGI  POST  examples

### ISSUE THREAD

**Issue by dbadb** [fbbdev/node-fastcgi#14]
Thanks for this nice package.  I  have a usage question which I haven't been able (yet) to tease out  of the documentation. My requirement to pull  the CGI CONTENT data from a  POST.  I see two fields in  the request obj:  cgiParams and  socket.params.   While I do  see  CONTENT_LENGTH, etc, I don't see the actual  CONTENT there.  

Is it  up to my code to perform a read on  the socket stream to obtain this?

I suppose this is either suggestion for docs or a missing  feature/example...  For example, if the example server just had a clause handling req.method  === "POST",  I'd probably be  good to  go.

**Comment by dbadb** [comment]
One additional datapoint: there may be a bug in node-fastcgi/lib/request.js, line  281..
CONTENT_LENGTH and CONTENT_TYPE are renamed in the header as nt-length and nt-type due to  the slice(5).

**Comment by dbadb** [comment]
So perhaps I've  resolved  my issue.. FYI: this little snippet  would  be helpful in your example:

 else if(req.method  === "POST") {
        res.writeHead(200, { 'Content-Type': 'text/plain' });
        var body="";
        req.on('data', function(data) {
            body  += data;
        });
        req.on('end', function() {
            res.end("POST working:" + body);
        });
    }

**Comment by fbbdev** [comment]
Thank you for the bug report, I'm opening a separate issue for that.
About POST method handling, just read the request body like you did; I can add the example. In general, this module strives to completely emulate the standard http module: code written for an http server should work without changes with FastCGI.

**Comment by fbbdev** [comment]
@dbadb thank you very much for reporting that bug. It was really critical but had not been noticed by anyone until now.
