### ISSUE TITLE
Compatibility with node ≥ 0.11.8?

### ISSUE THREAD

**Issue by ebraminio** [fbbdev/node-fastcgi#2]
I didn't dig the issue deeply but seems node-fastcgi somehow has problem with next version of node. My app doesn't work with lighttpd fcgi support and it just hangs browser request. It has same issue locally. I bisect the issue with [nvm](https://github.com/creationix/nvm) and find out that the issue is with 0.11.8 to latest version, 0.11.14. BTW thanks for node-fastcgi which is very useful for me.

Some useful links:
* http://blog.nodejs.org/2013/10/30/node-v0-11-8-unstable/
* https://github.com/joyent/node/commits/v0.11.8-release

**Comment by fbbdev** [comment]
Hi! Sorry for the delay. I'm looking into this, if it's my package's fault I'll try to fix it. BTW, I'd like to know how are you using node-fastcgi. I developed it to run node applications on a shared hosting service, never tought it would get so much attention.

**Comment by ebraminio** [comment]
Thank you. I have also some little tools that runs on a shared host like this [one](https://github.com/ebraminio/linkstranslator).

**Comment by ebraminio** [comment]
On [libuv](https://github.com/libuv/libuv/issues/124#issuecomment-69517149) we reached to the conclusion that the regression is coming from libuv/libuv@0d435a5. I don't if is possible to work around that locally but I think your insight there would be very useful also.

**Comment by fbbdev** [comment]
That's definitely a libuv issue. I'm posting updates to libuv/libuv#124. Closing this, since I think there's no possible workaround.
