### ISSUE TITLE
Unable to get FCGI_DATA content with req.socket.data for filter protocol

### ISSUE THREAD

**Issue by yookoala** [fbbdev/node-fastcgi#20]
According to [readme], I should access the data from `req.socket.data`. I have tried to run fastcgi service with the below code. But the `req.socket.data` object seems always `undefined`. 

I have confirmed that the data stream is sent by the "web server" in my test.

[readme]: https://github.com/fbbdev/node-fastcgi/blob/4f563626cb9c7cfc9b2971f8303c51781aa78863/README.md

```js

var fcgi = require('node-fastcgi');

responder = function (req, res) { ... }
authorizer = function (req, res) { ... }
filter = function (req, res) {
  // a simple filter to reverse the data string as
  // response body
  console.log('triggered filter');
  if (req.method === 'GET' || req.method === 'POST') {
    res.writeHead(200, { 'Content-Type': 'text/plain' });
    console.log('triggered filter: inside');
    var body = '';

    // ** code to test getting data
    req.on('filter', function () {
      console.log('get filter event: ',  req.socket.data);
    });
    req.on('data', function (data) {
      console.log('filter socket data inside: ', req.socket.data);
    })
    console.log('filter socket data outside: ', req.socket.data);

    req.on('end', function() {
      res.end(body);
    });
  } else {
    res.writeHead(501);
    res.end();
  }
}

fcgi.createServer(responder, authorizer, filter).listen('./node-fastcgi.sock');
```

**Comment by yookoala** [comment]
Got it finally. It should be `req.socket.dataStream` instead of `req.socket.data`. And I should listen to event 'data' in that stream. For example,

```javascript

 req.socket.dataStream.on('data', function (data) {
    res.end(someProcess(data.toString()))
});
```

**Comment by fbbdev** [comment]
Thank you for reporting this. Clearly, there is a mistake in the README. I'll fix it ASAP.

Also, like you have found out, `req.socket.dataStream` must be read through the usual readable stream interface.

This means that the `data` event could be fired more than once, so you should not use `res.end` in the callback and call `res.write` instead, then `res.end` when the `dataStream` emits the `end` event. You can also pipe data to any other writable or transform stream. https://nodejs.org/api/stream.html
