### ISSUE TITLE
Question: how to access request header in authorizer callback?

### ISSUE THREAD

**Issue by yookoala** [fbbdev/node-fastcgi#21]
I'm trying to write a authorizer. The idea is to examine the "Authorization" header value and determine if the user has access to the resource or not. I tried to access the request header:

1. According to documentation [http.Request API](https://nodejs.org/api/http.html), it provides a [getHeader(name)](https://nodejs.org/api/http.html#http_request_getheader_name) method. But seems the Request object of node-fastcgi do not provide the same interface. The `req.getHeader()` (as shown in below code) seems to be undefined.

2. I found that `req.headers` is an object, but it seems always empty.

```javascript
responder = function (req, res) { ... }
authorizer = function (req, res) {
  if (req.method === 'GET' || req.method === 'POST') {
    req.on('complete', function () {
      // **TODO: access "Authorization" header
      console.log('req', req.headers);
      // ---
      res.writeHead(403, { 'Content-Type': 'text/plain' });
      res.end('authorizer app: permission denied');
    });
  } else {
    res.writeHead(501, { 'Content-Type': 'text/plain' });
    res.end('unsupported method');
  }
}
filter = function (req, res) { ... }

fcgi.createServer(responder, authorizer, filter).listen('./node-fastcgi.sock');
```

So how should I access the request header in the authorizer callback?

**Comment by fbbdev** [comment]
The `getHeader` method is only supported by `http.ClientRequest` object which are used to actually _send_ http requests.

Since this is a _received_ request the API of [`http.IncomingMessage`](https://nodejs.org/api/http.html#http_class_http_incomingmessage) is supported, so you should find all headers in the `req.headers` object.

If the object is empty, either no headers have been received from the server, or something in node-fastcgi is not working. That would be strange, since the code is the same for responder and authorizer requests and usually works fine. Please, could you dump and post here the content of `req.socket.params`?

**Comment by fbbdev** [comment]
Please note that the response object comes with the `Content-Type` header already set to `text/plain`, so you can just do this:

```js
res.statusCode = 403;
res.end("authorizer app: permission denied");
```

Or even just call `res.deny()` for a 403 response without any message and `res.allow()` for a 200 response.

Also the `complete` event on request objects is only supported for compatibility with old node versions and you should not use it. The system ensures all headers have been received before invoking a responder/authorizer/filter callback so you can either read request data or respond immediately.

```js
authorizer = function (req, res) {
  if (req.method === 'GET' || req.method === 'POST') {
    console.log('req', req.headers);
    res.statusCode = 403;
    res.end('authorizer app: permission denied');
  } else {
    res.statusCode = 501;
    res.end('unsupported method');
  }
}
```

**Comment by yookoala** [comment]
Turns out I didn't map the header to the `FCGI_PARAMS`. My bad.

**Comment by fbbdev** [comment]
Ok. Is it working now?

**Comment by yookoala** [comment]
It is working now.

**Comment by yookoala** [comment]
I was writing a [golang library for writing fastcgi web server](https://github.com/yookoala/gofast). Since node-fastcgi is a library that properly implements all 3 roles (Responder, Filter, Authorizer), I use it to write example to test with.

If you're interested, the resulting example code is [here][example].

[example]: https://github.com/yookoala/gofast/tree/24931dbbd58b48a375b6f1fc9e392c6e78fb6422/example/nodejs

**Comment by fbbdev** [comment]
Nice! If you need links to the FastCGI spec I converted it to markdown and made it available at https://fast-cgi.github.io/spec

There's also [the original spec](https://fast-cgi.github.io/original) from fastcgi.com and [a dedicated repository](https://github.com/fast-cgi/spec) to suggest corrections.

**Comment by yookoala** [comment]
@fbbdev: Thanks. I was already reading that before :-)
