### ISSUE TITLE
Run php script behind fastcgi server and set up.

### ISSUE THREAD

**Issue by ganeshkbhat** [fbbdev/node-fastcgi#23]
I am trying to get this set up here. How do I run/set up PHP/perl scripts behind the node-fastcgi server like behind apache? Is that recommended or will it create a new process instance for every request for php if I use it.

**Comment by fbbdev** [comment]
I believe the only way to run php from node is by invoking the php interpreter as a separate process.

However, please note that `node-fastcgi` is not in any way a replacement for Apache. Conversely, its purpose is to allow running nodejs applications _as if they were fastcgi scripts, behind apache or nginx or a similar frontend_.

If you are interested in running node as a HTTP frontend for fastcgi scripts, you may check out [aredridel/fcgi-handler](https://github.com/aredridel/fcgi-handler) (the github version is newer than the npm one), or also [http-node-phpfpm](https://www.npmjs.com/package/http-node-phpfpm).
