### ISSUE TITLE
"Cannot remove headers after they are sent to the client" occured with Apache2.4 + mod_fastcgi

### ISSUE THREAD

**Issue by hkoba** [fbbdev/node-fastcgi#25]
Hi!

When I tried the example script in `README.md` (saved as `mytest.fcgi`) with Apache2.4 + mod_fastcgi + dynamic fcgi configuration, I got the following errors:

```
[Wed Apr 28 18:36:23.614135 2021] [:warn] [pid 106755:tid 106755] FastCGI: (dynamic) server "/var/www/cgi-bin/mytest.fcgi" started (pid 107080)
_http_outgoing.js:618
    throw new ERR_HTTP_HEADERS_SENT('remove');
    ^

Error [ERR_HTTP_HEADERS_SENT]: Cannot remove headers after they are sent to the client
    at Response.removeHeader (_http_outgoing.js:618:11)
    at Response._storeHeader (/usr/local/nodejs/versions/14.16.1/lib/node_modules/node-fastcgi/lib/response.js:44:18)
    at Response.writeHead (_http_server.js:328:8)
    at Server.<anonymous> (/var/www/cgi-bin/mytest.fcgi:19:17)
    at Server.emit (events.js:315:20)
    at Server.recordHandler (/usr/local/nodejs/versions/14.16.1/lib/node_modules/node-fastcgi/lib/server.js:293:22)
    at module.exports.<anonymous> (/usr/local/nodejs/versions/14.16.1/lib/node_modules/node-fastcgi/lib/server.js:271:34)
    at module.exports.emit (events.js:315:20)
    at processIncomingData (/usr/local/nodejs/versions/14.16.1/lib/node_modules/node-fastcgi/node_modules/fastcgi-stream/lib/stream.js:65:14)
    at Socket.<anonymous> (/usr/local/nodejs/versions/14.16.1/lib/node_modules/node-fastcgi/node_modules/fastcgi-stream/lib/stream.js:82:5) {
  code: 'ERR_HTTP_HEADERS_SENT'
}
[Wed Apr 28 18:36:24.157208 2021] [:warn] [pid 106755:tid 106755] FastCGI: (dynamic) server "/var/www/cgi-bin/mytest.fcgi" (pid 107080) terminated by calling exit with status '1'

```

The call of `removeHeader` is around here: https://github.com/fbbdev/node-fastcgi/blob/7022d3d354c8f3602639cc740a0b78cbf87c6deb/lib/response.js#L41-L45

When I commented out the above block, the script worked just fine for my environment. But of course, I know simply removing the block breaks existing tests. 

So, could you give me some advice to fix it?

Best regards,

hkoba.

**Comment by fbbdev** [comment]
Hello, and thank you for opening this issue.

First of all, I'm sorry for the huge delay in answering you. I had to take a long break from maintenance work on this package for personal reasons.

Unfortunately, I've not been able to reproduce the issue on my side. I tried reproducing your configuration with

  - Apache v2.4.57, latest release (from [docker hub](https://hub.docker.com/layers/library/httpd/2.4.57/images/sha256-2850eccbfe94484327e2107255242bd06fa596a2375860102e5d215d5943c9e6?context=explore));
  - mod_fastcgi v2.4.7.1 (from [@mcarbonneaux's mirror](https://github.com/FastCGI-Archives/mod_fastcgi), as the module is not officially available anymore);
  - default configuration for mod_fastcgi;
  - Node v18.13.0;
  - node-fastcgi v1.3.3 and v2.0.0;
  - the example code from my [README](https://github.com/fbbdev/node-fastcgi#example), taken verbatim.

I'm closing this issue for now. If it is still relevant to you, please feel free to reopen it. In that case, it would be important to provide the following information:

  - did you make any changes to the example code, and if yes, which ones?
  - which versions of apache, mod_fastcgi, node, node-fastcgi are you using?
  - how are apache and mod_fastcgi configured?
  - which request triggers the failure (URL, method, additional headers, body)?

Note however that mod_fastcgi has not been maintained for a long time. You might want to consider switching to the officially supported [mod_fcgid](https://httpd.apache.org/mod_fcgid/).

I'm sorry again for the long wait.
Fabio
