### ISSUE TITLE
Could not write to the response multiple times

### ISSUE THREAD

**Issue by trosos** [fbbdev/node-fastcgi#6]
I am having trouble with using two consecutive write()s into a response.

**Steps to reproduce:**
* In node, run the following:
```javascript
require("node-fastcgi").createServer(function (req, res) {
    res.writeHead(200, {"Content-Type": "text/html"});
    res.write("a");
    res.end("b");
}).listen("/tmp/socket");
```
* In another terminal, run the http server:
```
$ node_modules/.bin/fastcgi --port=8888 --socket=/tmp/socket &
```
* In yet another terminal, perform the http request:
```
$ wget -O - http://localhost:8888/ 2>/dev/null
```

**Expected results:**
I would expect wget to output "ab".

**Actual results:**
wget outputs only "a".

**Note 1:**
If I used nginx with disabled buffering ("fastcgi_buffering off;") instead of "node_modules/.bin/fastcgi", the fastcgi server would crash with:
```
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at exports._errnoException (util.js:870:11)
    at WriteWrap.afterWrite (net.js:769:14)
```
and wget would output only "a".

**Note 2:**
On the other hand, if I delay the call to res.end with setTimeout, everything works as expected:
```javascript
require("node-fastcgi").createServer(function (req, res) {
    res.writeHead(200, {"Content-Type": "text/html"});
    res.write("a");
    setTimeout(function () {
        res.end("b");
    });
}).listen("/tmp/socket");
```

**Comment by fbbdev** [comment]
I'm trying to debug this and I'm seeing some bad interaction between my module and node's http module. I've been able to get two writes working, but then three writes won't work. I don't understand exactly what's going on, and since my current implementation is a total mess I fear I'll have to rewrite it completely to fix this bug.

In the meantime you can work around this by buffering writes and submitting them in a single call to `res.end`, or you can put the call to `res.end` in the callback of the last call to `res.write` (e.g. `res.write("a", res.end.bind(res, "B"))`).

**Comment by fbbdev** [comment]
Resolved. Would you test the latest version from the master branch? It's a complete rewrite and I need to get some feedback before releasing it.

**Comment by trosos** [comment]
Thank you and sorry for the delay.

Now it seems to work except the fact that the body seems to be "chunked"-encoded. Repeating the experiment from my first post, I get:
```
$ wget -O - http://localhost:8888/ 2>/dev/null | hd
00000000  31 0d 0a 61 0d 0a 31 0d  0a 62 0d 0a 30 0d 0a 0d  |1..a..1..b..0...|
00000010  0a                                                |.|
00000011
```
while I expect wget to output only "ab".

This may be a client issue, however using nginx's fastcgi client I get analogous results.

**Comment by fbbdev** [comment]
Thank you for reporting this, it's my fault. I created a new issue: #8

**Comment by fbbdev** [comment]
It should be fixed now.
