### ISSUE TITLE
npm package description’s link to the spec is broken

### ISSUE THREAD

**Issue by binki** [fbbdev/node-fastcgi#9]
https://www.reddit.com/r/linuxadmin/comments/4bywjn/what_happened_to_fastcgicom/

The link http://www.fastcgi.com/drupal/node/6?q=node/22 found at https://www.npmjs.com/package/node-fastcgi and https://fbbdev.it/projects/node-fastcgi is broken.

**Comment by fbbdev** [comment]
Hello, I was aware of fastcgi.com being down, but I thought I had fixed the
links. I am hosting the spec at https://fast-cgi.github.com

Thank you for reporting the issue.

**Comment by binki** [comment]
Cool, thanks!
